### ISSUE TITLE
Xcode 7: "directory not found for option" warnings for /Frameworks folder

### ISSUE THREAD

**Issue by deemadden** [Quick/Nimble#166]
This is a dup of Quick issue #360 (https://github.com/Quick/Quick/issues/360).  Same problem, different project.

Building projects with Nimble included as a Cocoapod in the project under Xcode 7 beta 5 result in the warning:

ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'

Upon inspection, it doesn't appear as though the folder is there. I have seen this issue in custom framework contexts, and have been able to resolve it by removing the reference from Build Settings.

**Comment by jeffh** [comment]
Hey @deemadden,

Thanks for filing this issue. I don't know about Xcode 7 beta 5, but previous beta versions also gave this warning. Removing the extra framework include causes Quick & Nimble to not build (after full clean). I haven't looked at it since, but it would be idea to resolve.

**Comment by taiheng** [comment]
For some reason the location of the XCTest.framework has moved in Xcode 7 betas from the old path at

     /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks 

to

    /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks

It's possible to fix this temporarily until the framework paths are updated in the project by creating a symbolic link to the new path in terminal:

    cd /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk
    mkdir -p Developer/Library
    cd Developer/Library
    ln -s ../../../../Library/Frameworks/ Frameworks

I'm not sure if this is a permanent change or not and am hesitant to create a pull request correcting the path.

**Comment by AnthonyMDev** [comment]
@taiheng Since this seems to be the case now, after the GM Release, I'm willing to bet the change is permanent.

**Comment by taiheng** [comment]
I don't see this issue in cocoapods on swift-2.0 branch. I've fixed it for carthage builds in quick/nimble#185.

**Comment by AnthonyMDev** [comment]
Really? I'm still seeing this issue on the GM release with `2.0.0-rc3`. Maybe they have fixed it since `rc3`

**Comment by jeffh** [comment]
This should be resolved on `master` now (`swift-2.0` branch has been merged into `master` too). Closing.

Reopen/create a new issue if you still see this. Thanks!

**Comment by deju** [comment]
@taiheng  It works for me.
