### ISSUE TITLE
Build error for tvOS target. `BadInstructionException`.

### ISSUE THREAD

**Issue by AnthonyMDev** [Quick/Nimble#400]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Built a test target for tvOS using `Nimble` in my Podfile. Set 'Debug Executable' to `false` in my scheme.

### What actually happened instead?

Compiler Error. Target will not build.

`Use of undeclared type 'BadInstructionException`.

### Environment

List the software versions you're using:

 - Quick: none
 - Nimble: `6.0.1`
 - Xcode Version: `8.2.1`
 - Swift Version: `Xcode default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: `1.2.0`

**Comment by jeffh** [comment]
Hey @AnthonyMDev,

I think this is resolved with a CwlPreconditionTesting update. Let me know if this PR https://github.com/Quick/Nimble/pull/407 works

**Comment by jeffh** [comment]
This has been merged into master, closing. Feel free to reopen if this doesn't address the issue.

**Comment by kkiermasz** [comment]
Still doesn't work in version 8.1.1.
Tested with tvOS 9, 10 and 11.
